```{r}
library(arm)
library(mice)

# simulation sample size
n <- 1000

norm.data <- function(n) {
  x1 <- rnorm(n, 5, 1)
  x2 <- rnorm(n, 4, sqrt(2))
  x3 <- 1.2*x1 + 0.5*x2 + rnorm(n,0,1)
  x4 <- 0.7*x1 + 2.5*x3 + rnorm(n,0,1)
  x5 <- 3.2*x2 - 0.8*x3 + rnorm(n,0,1)
  x6 <- 0.5*x1 + 1.6*x5 + rnorm(n,0,1)
  x7 <- -1.5*x4 - 0.4*x6 + rnorm(n,0,1)
  x8 <- 0.6*x3 + 1.3*x5 + rnorm(n,0,1)
  x9 <- 2.5*x6 + x7   + rnorm(n,0,1)
  x10<- 1.8*x8 - 0.9*x9 + rnorm(n,0,1)
  return(data.frame(x1,x2,x3,x4,x5,x6,x7,x8,x9,x10))
}


miss.method <- function(data, method) {
  n <- nrow(data)
  
  if (method == "MCAR") {
    
    # set missing values for x3 to x10
    data$x3[sample(c(TRUE, FALSE), n, replace = TRUE, prob = c(0.3, 0.7))]  <- NA
    data$x4[sample(c(TRUE, FALSE), n, replace = TRUE, prob = c(0.3, 0.7))]  <- NA
    data$x5[sample(c(TRUE, FALSE), n, replace = TRUE, prob = c(0.3, 0.7))]  <- NA
    data$x6[sample(c(TRUE, FALSE), n, replace = TRUE, prob = c(0.3, 0.7))]  <- NA
    data$x7[sample(c(TRUE, FALSE), n, replace = TRUE, prob = c(0.3, 0.7))]  <- NA
    data$x8[sample(c(TRUE, FALSE), n, replace = TRUE, prob = c(0.3, 0.7))]  <- NA
    data$x9[sample(c(TRUE, FALSE), n, replace = TRUE, prob = c(0.3, 0.7))]  <- NA
    data$x10[sample(c(TRUE, FALSE), n, replace = TRUE, prob = c(0.3, 0.7))] <- NA
    
  } else if (method == "MAR") {
    
    p.miss <- invlogit(-2.25 + 0.2 * data$x1 + 0.1 * data$x2)
    
    # set missing values for x3 to x10
    data$x3[runif(n) < p.miss]  <- NA
    data$x4[runif(n) < p.miss]  <- NA
    data$x5[runif(n) < p.miss]  <- NA
    data$x6[runif(n) < p.miss]  <- NA
    data$x7[runif(n) < p.miss]  <- NA
    data$x8[runif(n) < p.miss]  <- NA
    data$x9[runif(n) < p.miss]  <- NA
    data$x10[runif(n) < p.miss] <- NA
  }
  
  return(data)
}


# compute inferences

library(mice)

inferences <- function(mice.data) {
  
  all.x <- c("x3", "x4", "x5", "x6", "x7", "x8", "x9", "x10")
  
  coef.list <- list(c("x1 + x2"), c("x1 + x3"), c("x2 + x3"), c("x1 + x5"),
                    c("x4 + x6"), c("x3 + x5"), c("x6 + x7"), c("x8 + x9"))
  
  all.inferences <- data.frame(
    x = all.x,
    mean.value = rep(0, length(all.x)),
    mean.CI.low = rep(0, length(all.x)),
    mean.CI.up = rep(0, length(all.x)),
    mean.var = rep(0, length(all.x)),
    beta0 = rep(0, length(all.x)),
    beta0.CI.low = rep(0, length(all.x)),
    beta0.CI.up = rep(0, length(all.x)),
    beta0.var = rep(0, length(all.x)),
    beta1 = rep(0, length(all.x)),
    beta1.CI.low = rep(0, length(all.x)),
    beta1.CI.up = rep(0, length(all.x)),
    beta1.var = rep(0, length(all.x)),
    beta2 = rep(0, length(all.x)),
    beta2.CI.low = rep(0, length(all.x)),
    beta2.CI.up = rep(0, length(all.x)),
    beta2.var = rep(0, length(all.x))
  )
  
  for (i in 1:length(all.x)) {
    
    # contain mean from regression model with only intercept
    mu.model <- with(mice.data, lm(as.formula(paste(all.x[i], "~ 1"))))
    mu.summary <- summary(pool(mu.model), conf.int = TRUE)
    
    # store mean and its CI
    all.inferences$mean.value[i] = mu.summary[1, 2]
    all.inferences$mean.CI.low[i] = mu.summary[1, 7]
    all.inferences$mean.CI.up[i] = mu.summary[1, 8]
    all.inferences$mean.var[i] = (mu.summary[1, 3])^2
    
    # inferences for coefficients
    coef.model <- with(mice.data, 
                       lm(as.formula(paste(all.x[i], "~", paste(coef.list[[i]])))))
    coef.summary <- summary(pool(coef.model), conf.int = TRUE)
    
    # store betas and their CI
    all.inferences$beta0[i] = coef.summary[1, 2]
    all.inferences$beta0.CI.low[i] = coef.summary[1, 7]
    all.inferences$beta0.CI.up[i] = coef.summary[1, 8]
    all.inferences$beta0.var[i] = (coef.summary[1, 3])^2
    
    all.inferences$beta1[i] = coef.summary[2, 2]
    all.inferences$beta1.CI.low[i] = coef.summary[2, 7]
    all.inferences$beta1.CI.up[i] = coef.summary[2, 8]
    all.inferences$beta1.var[i] = (coef.summary[2, 3])^2
    
    all.inferences$beta2[i] = coef.summary[3, 2]
    all.inferences$beta2.CI.low[i] = coef.summary[3, 7]
    all.inferences$beta2.CI.up[i] = coef.summary[3, 8]
    all.inferences$beta2.var[i] = (coef.summary[3, 3])^2
  }
  
  return(all.inferences)
}


# repeat it

mice.iteration <- function(n, miss, iterate) {
  
  output <- matrix(0, nrow = 32, ncol = 5)
  
  rownames(output) <- c("x3.mean","x3.beta0", "x3.beta1","x3.beta2",
                        "x4.mean","x4.beta0", "x4.beta1","x4.beta2",
                        "x5.mean","x5.beta0", "x5.beta1","x5.beta2",
                        "x6.mean","x6.beta0", "x6.beta1","x6.beta2",
                        "x7.mean","x7.beta0", "x7.beta1","x7.beta2",
                        "x8.mean","x8.beta0", "x8.beta1","x8.beta2",
                        "x9.mean","x9.beta0", "x9.beta1","x9.beta2",
                        "x10.mean","x10.beta0", "x10.beta1","x10.beta2")
  
  colnames(output) <- c("Count","Emp.Var", "Ave.Var", "Var.Ratio","Bias")
  
  mu.beta <- matrix(0, nrow = 32, ncol = iterate)
  all.var <- matrix(0, nrow = 32, ncol = iterate)
  
  true.value <- matrix(c(8, 0, 1.2, 0.5, 23.5, 0, 0.7, 2.5,
                         6.4, 0, 3.2, -0.8, 12.74, 0, 0.5, 1.6,
                         -40.346, 0, -1.5, -0.4, 13.12, 0, 0.6, 1.3,
                         -8.496, 0, 2.5, 1, 31.2624, 0, 1.8, -0.9), 
                       nrow = 32, ncol = 1, byrow = TRUE)
  
  for (i in 1:iterate) {
    
    data <- norm.data(n)
    
    if (miss == "MCAR") {
      mice.data <- miss.method(data, "MCAR")
      
      meth <- rep("norm", 10)
      meth[1:2] <- ""
    
    } else if (miss == "MAR") {
      mice.data <- miss.method(data, "MAR")
      
      meth <- rep("norm", 10)
      meth[1:2] <- ""
    }
    
    pred <- make.predictorMatrix(mice.data)
    # diag(pred) <- 0
    
    pred[ , ] = 0
    pred["x3", c("x1", "x2")] <- 1
    pred["x4", c("x1", "x3")] <- 1
    pred["x5", c("x2", "x3")] <- 1
    pred["x6", c("x1", "x5")] <- 1
    pred["x7", c("x4", "x6")] <- 1
    pred["x8", c("x3", "x5")] <- 1
    pred["x9", c("x6", "x7")] <- 1
    pred["x10", c("x8", "x9")] <- 1
    
    
    mice.result <- mice(mice.data, m = 10, method = meth, predictorMatrix = pred, 
                        maxit = 15, printFlag = FALSE, seed = i)
    
    result <- inferences(mice.result)
    
    for (k in seq(from = 4, to = 32, by = 4)) {
      
      mu.beta[k-3, i] = result$mean.value[k/4]
      mu.beta[k-2, i] = result$beta0[k/4]
      mu.beta[k-1, i] = result$beta1[k/4]
      mu.beta[k, i] = result$beta2[k/4]
      
      all.var[k-3, i] = result$mean.var[k/4]
      all.var[k-2, i] = result$beta0.var[k/4]
      all.var[k-1, i] = result$beta1.var[k/4]
      all.var[k, i] = result$beta2.var[k/4]
        
      if (result$mean.CI.up[k/4] >= true.value[k-3]  & 
          result$mean.CI.low[k/4] <= true.value[k-3]) {
        output[k-3, 1] = output[k-3, 1] + 1
      }
      if (result$beta0.CI.up[k/4] >= true.value[k-2]  & 
          result$beta0.CI.low[k/4] <= true.value[k-2]) {
        output[k-2, 1] = output[k-2, 1] + 1
      }
      if (result$beta1.CI.up[k/4] >= true.value[k-1]  & 
          result$beta1.CI.low[k/4] <= true.value[k-1]) {
        output[k-1, 1] = output[k-1, 1] + 1
      }
      if (result$beta2.CI.up[k/4] >= true.value[k]  & 
          result$beta2.CI.low[k/4] <= true.value[k]) {
        output[k, 1] = output[k, 1] + 1
      }
    }
  } 
  
  output[, 1] = output[, 1] / iterate
  
  for (i in seq(from = 4, to = 32, by = 4)) {
    for (j in (i-3):i) {
      output[j, 2] = var(mu.beta[j, 1:iterate], na.rm = TRUE)
      
      output[j, 3] = mean(all.var[j, 1:iterate], na.rm = TRUE)
      
      output[j, 4] = mean(all.var[j, 1:iterate], na.rm = TRUE) /
                     var(mu.beta[j, 1:iterate], na.rm = TRUE)

      output[j, 5] = mean(mu.beta[j, 1:iterate], na.rm = TRUE) - true.value[j, 1]
    }
  }
  
  return(output)
}

set.seed(123)
mcar.result <- mice.iteration(1000, "MCAR", 100)

set.seed(123)
mar.result <- mice.iteration(1000, "MAR", 100)

set.seed(123)
mcar.result1 <- mice.iteration(1000, "MCAR", 100)

set.seed(123)
mar.result2 <- mice.iteration(1000, "MAR", 100)


```




```{r}
## -------- Mean --------
cov_mcar_mean <- as.numeric(mcar.result[grepl("\\.mean$",  rownames(mcar.result)), "Count"])
cov_mar_mean  <- as.numeric(mar.result [grepl("\\.mean$",  rownames(mar.result )), "Count"])

boxplot(list(MCAR=cov_mcar_mean, MAR=cov_mar_mean),
        ylim=c(0.93, 0.99), names=c("MCAR: MICE","MAR: MICE"),
        ylab="Coverage", main="Normal Pattern Data: Mean", col = c("orange", "pink"),
        notch=FALSE, outline=FALSE, range=0, lwd=2, boxwex=0.6)
abline(h=.95, lty=2)



## -------- beta0 --------
cov_mcar_b0 <- as.numeric(mcar.result[grepl("\\.beta0$", rownames(mcar.result)), "Count"])
cov_mar_b0  <- as.numeric(mar.result [grepl("\\.beta0$", rownames(mar.result )), "Count"])

boxplot(list(MCAR=cov_mcar_b0, MAR=cov_mar_b0),
        ylim=c(0.91, 1), names=c("MCAR: MICE","MAR: MICE"),
        ylab="Coverage", main="Normal Pattern Data: Beta0", col = c("orange", "pink"),
        notch=FALSE, outline=FALSE, range=0, lwd=2, boxwex=0.6)
abline(h=.95, lty=2)

## -------- beta1 --------
cov_mcar_b1 <- as.numeric(mcar.result[grepl("\\.beta1$", rownames(mcar.result)), "Count"])
cov_mar_b1  <- as.numeric(mar.result [grepl("\\.beta1$", rownames(mar.result )), "Count"])

boxplot(list(MCAR=cov_mcar_b1, MAR=cov_mar_b1),
        ylim=c(0.91, 0.99), names=c("MCAR: MICE","MAR: MICE"),
        ylab="Coverage", main="Normal Pattern Data: Beta1", col = c("orange", "pink"),
        notch=FALSE, outline=FALSE, range=0, lwd=2, boxwex=0.6)
abline(h=.95, lty=2)


## -------- beta2 --------
cov_mcar_b2 <- as.numeric(mcar.result[grepl("\\.beta2$", rownames(mcar.result)), "Count"])
cov_mar_b2  <- as.numeric(mar.result [grepl("\\.beta2$", rownames(mar.result )), "Count"])

boxplot(list(MCAR=cov_mcar_b2, MAR=cov_mar_b2),
        ylim=c(0.91, 1), names=c("MCAR: MICE","MAR: MICE"),
        ylab="Coverage", main="Normal Pattern Data: Beta2", col = c("orange", "pink"),
        notch=FALSE, outline=FALSE, range=0, lwd=2, boxwex=0.6)
abline(h=.95, lty=2)

```


```{r}
## -------- MEAN --------
vr_mcar_mean <- as.numeric(mcar.result[grepl("\\.mean$",  rownames(mcar.result)), "Var.Ratio"])
vr_mar_mean  <- as.numeric(mar.result [grepl("\\.mean$",  rownames(mar.result )), "Var.Ratio"])

boxplot(list(MCAR=vr_mcar_mean, MAR=vr_mar_mean),
        ylim=c(0.92, 1.45), names=c("MCAR: MICE","MAR: MICE"),
        ylab="VarianceRatio", main="Normal Pattern Data: Mean", col = c("orange", "pink"),
        notch=FALSE, outline=FALSE, range=0, lwd=2, boxwex=0.6)
abline(h=1, lty=2)



## -------- beta0 --------
vr_mcar_b0 <- as.numeric(mcar.result[grepl("\\.beta0$", rownames(mcar.result)), "Var.Ratio"])
vr_mar_b0  <- as.numeric(mar.result [grepl("\\.beta0$", rownames(mar.result )), "Var.Ratio"])

boxplot(list(MCAR=vr_mcar_b0, MAR=vr_mar_b0),
        ylim=c(0.8, 1.35), names=c("MCAR: MICE","MAR: MICE"),
        ylab="VarianceRatio", main="Normal Pattern Data: Beta0", col = c("orange", "pink"),
        notch=FALSE, outline=FALSE, range=0, lwd=2, boxwex=0.6)
abline(h=1, lty=2)

## -------- beta1 --------
vr_mcar_b1 <- as.numeric(mcar.result[grepl("\\.beta1$", rownames(mcar.result)), "Var.Ratio"])
vr_mar_b1  <- as.numeric(mar.result [grepl("\\.beta1$", rownames(mar.result )), "Var.Ratio"])

boxplot(list(MCAR=vr_mcar_b1, MAR=vr_mar_b1),
        ylim=c(0.8, 1.2), names=c("MCAR: MICE","MAR: MICE"),
        ylab="VarianceRatio", main="Normal Pattern Data: Beta1", col = c("orange", "pink"),
        notch=FALSE, outline=FALSE, range=0, lwd=2, boxwex=0.6)
abline(h=1, lty=2)


## -------- beta2 --------
vr_mcar_b2 <- as.numeric(mcar.result[grepl("\\.beta2$", rownames(mcar.result)), "Var.Ratio"])
vr_mar_b2  <- as.numeric(mar.result [grepl("\\.beta2$", rownames(mar.result )), "Var.Ratio"])

boxplot(list(MCAR=vr_mcar_b2, MAR=vr_mar_b2),
        ylim=c(0.65, 1.4), names=c("MCAR: MICE","MAR: MICE"),
        ylab="VarianceRatio", main="Normal Pattern Data: Beta2", col = c("orange", "pink"),
        notch=FALSE, outline=FALSE, range=0, lwd=2, boxwex=0.6)
abline(h=1, lty=2)


```


```{r}
## -------- MEAN --------
bias_mcar_mean <- as.numeric(mcar.result[grepl("\\.mean$",  rownames(mcar.result)), "Bias"])
bias_mar_mean  <- as.numeric(mar.result [grepl("\\.mean$",  rownames(mar.result )), "Bias"])

boxplot(list(MCAR=bias_mcar_mean, MAR=bias_mar_mean),
        ylim=c(-0.05, 0.075), names=c("MCAR: MICE","MAR: MICE"),
        ylab="Bias", main="Normal Pattern Data: Mean", col = c("orange", "pink"),
        notch=FALSE, outline=FALSE, range=0, lwd=2, boxwex=0.6)
abline(h=0, lty=2)



## -------- beta0 --------
bias_mcar_b0 <- as.numeric(mcar.result[grepl("\\.beta0$", rownames(mcar.result)), "Bias"])
bias_mar_b0  <- as.numeric(mar.result [grepl("\\.beta0$", rownames(mar.result )), "Bias"])

boxplot(list(MCAR=bias_mcar_b0, MAR=bias_mar_b0),
        ylim=c(-0.03, 0.03), names=c("MCAR: MICE","MAR: MICE"),
        ylab="Bias", main="Normal Pattern Data: Beta0", col = c("orange", "pink"),
        notch=FALSE, outline=FALSE, range=0, lwd=2, boxwex=0.6)
abline(h=0, lty=2)

## -------- beta1 --------
bias_mcar_b1 <- as.numeric(mcar.result[grepl("\\.beta1$", rownames(mcar.result)), "Bias"])
bias_mar_b1  <- as.numeric(mar.result [grepl("\\.beta1$", rownames(mar.result )), "Bias"])

boxplot(list(MCAR=bias_mcar_b1, MAR=bias_mar_b1),
        ylim=c(-0.0085, 0.0055), names=c("MCAR: MICE","MAR: MICE"),
        ylab="Bias", main="Normal Pattern Data: Beta1", col = c("orange", "pink"),
        notch=FALSE, outline=FALSE, range=0, lwd=2, boxwex=0.6)
abline(h=0, lty=2)


## -------- beta2 --------
bias_mcar_b2 <- as.numeric(mcar.result[grepl("\\.beta2$", rownames(mcar.result)), "Bias"])
bias_mar_b2  <- as.numeric(mar.result [grepl("\\.beta2$", rownames(mar.result )), "Bias"])

boxplot(list(MCAR=bias_mcar_b2, MAR=bias_mar_b2),
        ylim=c(-0.002, 0.003), names=c("MCAR: MICE","MAR: MICE"),
        ylab="Bias", main="Normal Pattern Data: Beta2", col = c("orange", "pink"),
        notch=FALSE, outline=FALSE, range=0, lwd=2, boxwex=0.6)
abline(h=0, lty=2)


```



















